files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero: 1
  class-name-format:
    - 2
    - convention: '^_?[a-z-]+(-{2}([a-z-]+|[A-Z-]+))?$'
    - convention-explanation: 'Your selector needs to follow hyphenatedbem with an allowance of all uppercase on the modifier.'
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 0
    - include: false
  function-name-format:
    - 2
    - convention: hyphenatedlowercase
  hex-length:
  - 2
  - style: short
  hex-notation:
    - 2
    - style: lowercase
  id-name-format: 1
  indentation:
    - 2
    - size: 4
  leading-zero:
    - 2
    - include: false
  mixin-name-format:
    - 2
    - convention: hyphenatedlowercase
  mixins-before-declarations: 2
  nesting-depth:
    - 2
    - max-depth: 5
  no-color-keywords: 2
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-invalid-hex: 0
  no-misspelled-properties:
    - 2
    - extra-properties: []
  no-qualifying-elements: 1
  no-trailing-zero: 2
  no-url-protocols: 0
  placeholder-in-extend: 2
  placeholder-name-format: 2
  property-sort-order: 0
  quotes:
    - 2
    - style: double
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-colon: 2
  space-after-comma: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 2
    - convention: hyphenatedlowercase
  zero-unit: 2